### ISSUE TITLE
Crash on start: Symbol lookup error

### ISSUE THREAD

**Issue by notxenonbox** [ruslang02/discord-qt#38]
I am on arch linux and I installed the `discord-qt` AUR package. My system is up to date

Here is the output when I run discord-qt:
```
neo@fukushima ~
λ Discord-Qt
[warn] [PreLaunchConfigManager] Could not load config file.
Discord-Qt: symbol lookup error: /usr/lib/discord-qt/dist/nodegui_core.node: undefined symbol: _ZdlPvm, version Qt_5
```

If any more information is needed, just ask.

**Comment by ruslang02** [comment]
I could only recommend installing `discord-qt-appimage` package, the `discord-qt` package seems to be broken by some maintainer.

**Comment by notxenonbox** [comment]
I cannot use the appimage with wayland, it has an outdated QT version.

**Comment by Zaedus** [comment]
Yes, this same exact issue happened to me too. I installed the appimage and it worked fine, but I'm on xorg. I can recommend Xwayland, if that is at all possible.

**Comment by notxenonbox** [comment]
Thanks for the Xwayland tip, but I would like to avoid that, I need to set a environment for that. I know it's a small inconvenience, but I would like to run full wayland, that's the reason I am searching for a custom client in the first place.

**Comment by ruslang02** [comment]
You could try building the client by yourself, as there are really no problems running it on Wayland or Mir.. The only thing to consider is to build NodeGui with your system Qt libraries rather than miniqt ones that nodegui downloads on install. If I'm not wrong you need to set the QT_INSTALL_DIR variable when running npm install.

**Comment by notxenonbox** [comment]
Thanks for responding I will look into that.
